S8#2
tyroncoop/ssibrowser pull request #24
Opened 2022-05-10 10:08 UTC by DevPH-Wistkey

2022-05-10 11:53 UTC, tralkan commented
Hi @DevPH-Wistkey, please update this PR by fetching the latest tyroncoop:s8 - thanks!

2022-05-11 02:46 UTC, DevPH-Wistkey commented
Already merged the latest update from tyroncoop/s8, please let me know if there's something I missed. Thanks! @tralkan

2022-05-11 03:46 UTC, DevPH-Wistkey commented
Also, I put persist currency task on this PR because this PR is related to balance. But we'll work with one PR per task for upcoming tasks.

2022-05-11 13:57 UTC, tralkan requested changes
Some comments pending.

2022-05-12 02:15 UTC, DevPH-Wistkey commented on src/hooks/isController.ts
> +      setTimeout(() => {
Hi @tralkan yes we need it, because it will cause a glitch when the page redirects and shows toast at the same time.

2022-05-13 01:28 UTC, tralkan approved these changes

2022-05-13 01:31 UTC, merged