S19
tyroncoop/ssibrowser pull request #80
Opened 2022-10-12 09:49 UTC by devwistkey

2022-10-20 02:09 UTC, tralkan requested changes

2022-10-20 11:17 UTC, devwistkey commented on components/SSI/DIDxWallet/SocialRecovery/Recover/index.tsx
> +            if (parseFloat(resolvedInfo?.version?.slice(-5)!) >= 5.8) {
hi, yes

2022-10-20 11:20 UTC, devwistkey commented on components/AddLiquidity/index.tsx
> +                    <Selector option={option} onChange={handleOnChange} />
It has default value from the selector itself @tralkan

2022-10-21 01:12 UTC, tralkan requested changes

2022-10-21 02:27 UTC, devwistkey commented on components/SSI/DIDxWallet/SocialRecovery/Recover/index.tsx
> +            if (parseFloat(resolvedInfo?.version?.slice(-5)!) >= 5.8) {
I found DIDxWALLET_5.10.0 without 'v'. So I'll start from '_'

2022-10-21 03:37 UTC, devwistkey commented on components/SSI/DIDxWallet/Wallet/DIDOperations/SocialRecovery/index.tsx
> +                toast.error('Repeated username are not allowed', {
done

2022-10-21 03:37 UTC, devwistkey commented on components/SSI/DIDxWallet/SocialRecovery/Recover/index.tsx
> +    const resolveDid = async (_username: string) => {
done

2022-10-21 03:38 UTC, devwistkey commented on components/SSI/AddFunds/OriginatorAddress/index.tsx
> +        } else if (input.includes('.did') || input.includes('.ssi')) {
done

2022-10-21 18:00 UTC, tralkan approved these changes

2022-10-21 18:07 UTC, merged

2022-10-24 04:09 UTC, devwistkey commented on components/SSI/DIDxWallet/SocialRecovery/Recover/index.tsx
> +        var ver = resolvedInfo?.version?.split('_')[1]!
done

2022-10-24 04:09 UTC, devwistkey commented on components/SSI/DIDxWallet/Wallet/DIDOperations/SocialRecovery/index.tsx
> +    const versionAbove58 = () => {
done

2022-10-24 04:22 UTC, devwistkey commented on components/SSI/SBTxWallet/Wallet/index.tsx
> +                .toLowerCase()
Hi, yes. I just tested it and it can resolve soul@tyron.ssi